Middle section mobile website
VaheStepanyan100/Portfolio-mobile-first pull request #2
Opened 2023-03-27 20:27 UTC by VaheStepanyan100

-  Parse a Figma design to create a UI.
- Use Flexbox to place elements in the page.
- Use CSS Grid to place elements in the page.
- Build a personal portfolio site.

2023-03-27 21:50 UTC, levy002 requested changes
## Hello @VaheStepanyan100   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Highlights
- Professional PR :heavy_check_mark: 
- Professional README :heavy_check_mark: 

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-27 21:50 UTC, levy002 commented on styles.css
> +}
- [ ] KIndly make sure each project card content is aligned on the page using the CSS `flexbox` in order to meet the project requirements. Not only that, CSS `flexbox` will help in the future to maintain easily page responsiveness. Kindly read [this lesson](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Basic_Concepts_of_Flexbox) for more information.

- [ ] KIndly make sure to give the project card the same `background-color` as the one on the provided Figma design.

    - ### YOUR DESIGN
    
    ![image](https://user-images.githubusercontent.com/87197412/228072263-8668deff-2901-43ac-9e52-fd3d639a2ca5.png)

    - ### FIGMA DESIGN
    
    ![image](https://user-images.githubusercontent.com/87197412/228072366-87d032b9-2109-4e94-85eb-62ccc5dc6368.png)

2023-03-27 21:50 UTC, levy002 commented on index.html
> +          <div class="contactTitle"><a href="#">LET’S CONNECT</a></div>
- [ ] KIndly make sure the `LET'S CONNECT` title is rendered on the page using heading tags `h2, h3, h4, hx. ..` in order to follow best HTML practices and meet the project's requirements a well.

2023-03-27 21:50 UTC, levy002 commented on index.html
> +          </div>
- [ ] KIndly make sure `Languages`, `Frameworks`, and `Skills` are wrapped into the `ul` tag and each one is wrapped into the `li` tag in order to follow best HTML practices and meet the project's requirements a well.

2023-03-27 21:50 UTC, levy002 commented on styles.css
> +
- [ ] Kindly make sure your `main` section covers all widths of the page. You can achieve that by making sure the body doesn't have any `padding` or `margin`.

2023-03-27 21:50 UTC, levy002 commented on styles.css
> +}
- [ ] Kindly make sure to add the padding on all sides of the language card in order to meet the provided Figma design.

   ### YOUR DESIGN
    ![image](https://user-images.githubusercontent.com/87197412/228074111-50f8c898-e7ce-4e00-bb50-96556fbcd8c1.png)


   ### FIGMA DESIGN
    ![image](https://user-images.githubusercontent.com/87197412/228074047-64a37073-3b4f-4752-a724-cf93fac6a0ea.png)

2023-03-27 21:50 UTC, levy002 commented on index.html
> +          <ul class="lets-connect">
- [ ] KIndly make sure to provide enough space between this title and the social media links container in order to look like the provided Figma design as much as possible.


    - ### YOUR DESIGN
    
    ![image](https://user-images.githubusercontent.com/87197412/228074654-288af73a-89f9-4e62-855d-eb347c947f22.png)

    - ### FIGMA DESIGN
    
    ![image](https://user-images.githubusercontent.com/87197412/228074713-0d820f01-a871-48d6-86c3-daae1c43dcb6.png)

2023-03-28 10:35 UTC, OyePriscilla requested changes
Hi @VaheStepanyan100 👍 👍 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![so-close-so-close-seth-meyers](https://user-images.githubusercontent.com/103386183/196425724-8ca5825c-b02a-4983-b976-4bd0a2f70f9a.gif)

 ## Highlights
Displayed the project section with CSS flex property ✔️
Used images and background-image to enhance the look of the website ✔️
Made some required change ✔️


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-28 10:35 UTC, OyePriscilla commented on index.html
> +                <span>Skills</span>
- [ ] Please kindly wrap the list of the technology categories ("Languages", "Frameworks" and "Skills") in a `ul`, each of them in a `li` as suggested earlier. 👍 

- [optional] For good user interaction, kindly design this technologies categories according to the template. 👍 

## Your design
<img width="262" alt="Untitled" src="https://user-images.githubusercontent.com/103386183/228209517-2ae05b03-3f2d-450f-b69c-6800084a920c.png">

2023-03-28 11:03 UTC, OyePriscilla approved these changes
Hi @VaheStepanyan100 👏 👏 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![200](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif)

## Highlights
Displayed the project section with CSS flex property ✔️
Used images and background-image to enhance the look of the website ✔️
Made some required change ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-29 09:00 UTC, merged